// Electron — Steam Deck installer-freshness check (main process).
//
// The in-app updater replaces the AppImage but CANNOT rewrite the launcher wrapper
// (run-terraforming-mars.sh) — that is generated by scripts/steamdeck/install-steamdeck.sh.
// So when the installer changes (e.g. new perf env knobs baked into the wrapper), the user
// must MANUALLY re-run `curl … | bash`, which is easy to forget. To catch it:
//   • the installer stamps the wrapper with the sha256 of the installer it was generated from
//     (TM_INSTALLER_SHA) plus the raw URL it lives at (TM_INSTALLER_URL);
//   • at startup THIS module fetches the CURRENT installer from that URL, hashes it, and if the
//     hash differs surfaces a NON-blocking notice ("re-run the installer") — via the log AND the
//     renderer footer (desktop:getInstallerNotice).
//
// Best-effort: any network / hash failure → NOT stale (never a false alarm). Linux only.

import {ipcMain} from 'electron';
import * as crypto from 'crypto';

export interface InstallerNotice {
  stale: boolean;
  /** Why we flagged it — 'installer-changed' (hash mismatch vs GitHub) or 'legacy-wrapper'
   *  (launched by a wrapper that predates this check, so it carries no stamp). */
  reason?: 'installer-changed' | 'legacy-wrapper';
  installerUrl?: string;
}

/**
 * PURE decision (no electron / network) — unit-testable. Given the sha the wrapper was
 * stamped with, the freshly-fetched remote sha, and whether we were launched by a wrapper
 * at all, decide whether the installed wrapper is stale:
 *   • stamped AND remote present AND differ → 'installer-changed'
 *   • stamped present, remote missing (offline / fetch failed) → NOT stale (no false alarm)
 *   • no stamp but launched by a wrapper → 'legacy-wrapper' (old wrapper predating this check)
 *   • otherwise (not a wrapper launch) → NOT stale
 */
export function evaluateInstaller(
  input: {stampedSha?: string; remoteSha?: string; launchedByWrapper: boolean},
): InstallerNotice {
  const stamped = (input.stampedSha ?? '').trim().toLowerCase();
  const remote = (input.remoteSha ?? '').trim().toLowerCase();
  if (stamped !== '') {
    if (remote !== '' && remote !== stamped) {
      return {stale: true, reason: 'installer-changed'};
    }
    return {stale: false};
  }
  if (input.launchedByWrapper) {
    return {stale: true, reason: 'legacy-wrapper'};
  }
  return {stale: false};
}

export function sha256(text: string): string {
  return crypto.createHash('sha256').update(text, 'utf8').digest('hex');
}

let notice: InstallerNotice = {stale: false};

async function fetchRemoteSha(url: string, timeoutMs = 8000): Promise<string | undefined> {
  try {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), timeoutMs);
    const res = await fetch(url, {signal: controller.signal});
    clearTimeout(timer);
    if (!res.ok) {
      return undefined;
    }
    return sha256(await res.text());
  } catch {
    return undefined;
  }
}

/** Run the check once at startup. Linux only; best-effort; logs the outcome. Stores the result
 *  for the renderer to pull via desktop:getInstallerNotice. */
export async function runInstallerCheck(): Promise<InstallerNotice> {
  if (process.platform !== 'linux') {
    notice = {stale: false};
    return notice;
  }
  const stampedSha = (process.env.TM_INSTALLER_SHA ?? '').trim();
  const url = (process.env.TM_INSTALLER_URL ?? '').trim();
  const launchedByWrapper = process.env.TM_RESTART_SUPPORTED === '1';
  // Only the hash-mismatch branch needs the network; the legacy-wrapper branch is env-only.
  const remoteSha = (stampedSha !== '' && url !== '') ? await fetchRemoteSha(url) : undefined;
  notice = {
    ...evaluateInstaller({stampedSha, remoteSha, launchedByWrapper}),
    installerUrl: url !== '' ? url : undefined,
  };
  // eslint-disable-next-line no-console
  console.log(
    `[installer] freshness check — stale=${notice.stale}` +
    (notice.reason !== undefined ? ` reason=${notice.reason}` : '') +
    (notice.stale ? ' — RE-RUN scripts/steamdeck/install-steamdeck.sh (curl … | bash)' : ''),
  );
  return notice;
}

/** Wire the IPC the preload's desktopBridge calls. Call once, after app ready. */
export function registerInstallerCheckIpc(): void {
  ipcMain.handle('desktop:getInstallerNotice', () => notice);
}
