import {BoardName} from '@/common/boards/BoardName';
import {BoardLayoutSpace, BoardLayouts} from '@/common/boards/BoardLayout';
import boardLayoutsJson from '@/genfiles/boardLayouts.json';

/**
 * The client's static board layouts (real per-hex geometry/bonuses of every
 * Mars board), generated by make:cards from the server board definitions.
 * See `common/boards/BoardLayout.ts` for the shape contract.
 */
const LAYOUTS = boardLayoutsJson as unknown as BoardLayouts;

export function clientBoardLayout(name: BoardName): ReadonlyArray<BoardLayoutSpace> {
  return LAYOUTS[name] ?? [];
}
