/*
 * CARD ART — the ONE resolution point for per-card artwork.
 *
 * Art files live in `assets/card-images/<cardNumber>.webp` (the card's
 * `metadata.cardNumber` — '014', 'X31', 'P36', …), with a shared generic
 * fallback `-1.webp`. Which files actually EXIST is baked at build time into
 * `src/genfiles/cardArtManifest.json` (generated by
 * `src/tools/make_card_art_manifest.ts`, chained into `make:cards`), so
 * resolution never fires a 404 per missing file.
 *
 * Two consumers, two contracts:
 *  - `cardArtUrl` (the ORIGINAL contract, kept): returns a URL only for
 *    cards that have REAL art, undefined otherwise — legacy surfaces keep
 *    their type-gradient body when this returns undefined, never a muddy
 *    placeholder.
 *  - `premiumCardArt` (the premium face renderer): ALWAYS resolves — a card
 *    without its own art gets the shared fallback `-1.webp` (the premium
 *    layout reserves an art viewport, so an empty frame would read broken).
 *
 * URLs are project-relative (`assets/...`) — served by ServeAsset on web,
 * by the app:// protocol in Electron (both already whitelist .webp under
 * assets/); same pattern as `ma/maArt.ts`.
 */

import {CardName} from '@/common/cards/CardName';
import {getCard} from '@/client/cards/ClientCardManifest';
// @ts-ignore cardArtManifest.json doesn't exist until make:cards runs
import artManifest from '@/genfiles/cardArtManifest.json' assert {type: 'json'};

export const CARD_ART_FALLBACK_URL = 'assets/card-images/-1.webp';

/**
 * ART TIERS. Every art ships in two builds of the same picture:
 *  - FULL  — `assets/card-images/<key>.webp`, 1536×1024 (~6 MiB decoded);
 *  - THUMB — `assets/card-images/thumb/<key>.webp`, 512×341 (~0.7 MiB
 *    decoded), generated 1:1 from the full set by
 *    `scripts/make-card-art-thumbs.mjs` (chained into `make:cards`).
 *
 * The thumb tier exists for DENSE card surfaces — tableau piles, category
 * grids, flight proxies — where the face paints at ≤ ~520 CSS px width and
 * full-res art buys only decode spikes and resident GPU memory (a 200-card
 * tableau's difference is hundreds of MiB on a Steam-Deck-class device).
 * Large renders (fullscreen viewer, the single-card stage, hero cinematics)
 * stay on FULL. The `<img>` failure chain heals a missing thumb by falling
 * back to the full URL (see PremiumCardArt), so a stale checkout can never
 * lose a picture.
 */
export type CardArtTier = 'full' | 'thumb';

/**
 * The widest CSS-px card box (320 × zoom, ui-scale folded in) the thumb tier
 * may serve. 512 source px over ≤520 CSS px keeps ≥0.98 source-px per CSS px
 * — visually indistinguishable from full-res at that size; anything wider
 * takes the full file.
 */
export const ART_THUMB_MAX_CSS_WIDTH = 520;

/** The tier-specific URL of an already-resolved art. */
export function cardArtUrlAtTier(url: string, tier: CardArtTier): string {
  if (tier === 'thumb') {
    return url.replace('assets/card-images/', 'assets/card-images/thumb/');
  }
  return url;
}

/** The tier a card box of `cssWidth` px should paint (pure, deterministic). */
export function artTierForWidth(cssWidth: number): CardArtTier {
  return cssWidth > ART_THUMB_MAX_CSS_WIDTH ? 'full' : 'thumb';
}

const available: ReadonlySet<string> = new Set(artManifest as Array<string>);

function artKey(name: CardName): string | undefined {
  const metadata = getCard(name)?.metadata;
  if (metadata === undefined) {
    return undefined;
  }
  const num = metadata.cardNumber;
  if (num !== undefined && available.has(num)) {
    return num;
  }
  // A reimplemented card (a promo reissue of a base card) with no art of its
  // own borrows the base card's illustration rather than the generic fallback.
  if (metadata.reimplements !== undefined) {
    return artKey(metadata.reimplements);
  }
  return undefined;
}

/** URL of the card's REAL art, or undefined when the card has none (legacy contract). */
export function cardArtUrl(name: CardName): string | undefined {
  const key = artKey(name);
  return key === undefined ? undefined : `assets/card-images/${key}.webp`;
}

export type PremiumCardArt = {
  /** Always resolves — the fallback URL when the card has no art of its own. */
  url: string;
  /** True when `url` is the shared generic fallback, not per-card art. */
  fallback: boolean;
};

/** Art for the premium card face — always resolves (fallback baked in). */
export function premiumCardArt(name: CardName): PremiumCardArt {
  const url = cardArtUrl(name);
  return url === undefined ?
    {url: CARD_ART_FALLBACK_URL, fallback: true} :
    {url, fallback: false};
}

/**
 * Decode a card's art UP FRONT, before a cinematic mounts a premium face for
 * it. A face that mounts on a not-yet-decoded webp paints a BLACK body for a
 * frame or two — very visible on a card that holds still (a discard's turn, a
 * draw's flip). `premiumCardArt` always resolves (real art, else the shared
 * fallback), so both cases warm.
 *
 * ⚠️ FETCHING IS NOT DECODING, and only decoding is what the caller wants.
 * `img.src = …` guarantees the BYTES arrive; the picture still does not exist
 * until the browser has rasterized it, and these are ~1536px webps. That gap
 * is measured in hundreds of ms and is exactly the width of a cinematic: the
 * hand-open flight showed a shelf of art-less cards on its FIRST run and full
 * art on every later one, because the first paint was doing the decoding.
 * `decode()` moves that work ahead of the scene, where there is time for it.
 *
 * Fire-and-forget by contract: a warm-up may never gate a cinematic, and a
 * rejected decode is the `<img>`'s own fallback chain's business
 * (PremiumCardArt.onError). Bounded and a no-op under JSDOM/SSR. Every console
 * scene that spawns card proxies should call it at ARM time, which is where
 * the round-trip pays for the decode.
 */
export function preloadPremiumCardArt(names: ReadonlyArray<CardName>): void {
  if (typeof Image === 'undefined') {
    return; // JSDOM / SSR — nothing to warm.
  }
  for (const name of names) {
    const img = new Image();
    img.src = premiumCardArt(name).url;
    void img.decode?.().catch(() => undefined);
  }
}
