/*
 * CARD ART — the ONE resolution point for per-card artwork.
 *
 * Art files live in `assets/card-images/<cardNumber>.webp` (the card's
 * `metadata.cardNumber` — '014', 'X31', 'P36', …), with a shared generic
 * fallback `-1.webp`. Which files actually EXIST is baked at build time into
 * `src/genfiles/cardArtManifest.json` (generated by
 * `src/tools/make_card_art_manifest.ts`, chained into `make:cards`), so
 * resolution never fires a 404 per missing file.
 *
 * Two consumers, two contracts:
 *  - `cardArtUrl` (the ORIGINAL contract, kept): returns a URL only for
 *    cards that have REAL art, undefined otherwise — legacy surfaces keep
 *    their type-gradient body when this returns undefined, never a muddy
 *    placeholder.
 *  - `premiumCardArt` (the premium face renderer): ALWAYS resolves — a card
 *    without its own art gets the shared fallback `-1.webp` (the premium
 *    layout reserves an art viewport, so an empty frame would read broken).
 *
 * URLs are project-relative (`assets/...`) — served by ServeAsset on web,
 * by the app:// protocol in Electron (both already whitelist .webp under
 * assets/); same pattern as `ma/maArt.ts`.
 */

import {CardName} from '@/common/cards/CardName';
import {getCard} from '@/client/cards/ClientCardManifest';
// @ts-ignore cardArtManifest.json doesn't exist until make:cards runs
import artManifest from '@/genfiles/cardArtManifest.json' assert {type: 'json'};

export const CARD_ART_FALLBACK_URL = 'assets/card-images/-1.webp';

const available: ReadonlySet<string> = new Set(artManifest as Array<string>);

function artKey(name: CardName): string | undefined {
  const metadata = getCard(name)?.metadata;
  if (metadata === undefined) {
    return undefined;
  }
  const num = metadata.cardNumber;
  if (num !== undefined && available.has(num)) {
    return num;
  }
  // A reimplemented card (a promo reissue of a base card) with no art of its
  // own borrows the base card's illustration rather than the generic fallback.
  if (metadata.reimplements !== undefined) {
    return artKey(metadata.reimplements);
  }
  return undefined;
}

/** URL of the card's REAL art, or undefined when the card has none (legacy contract). */
export function cardArtUrl(name: CardName): string | undefined {
  const key = artKey(name);
  return key === undefined ? undefined : `assets/card-images/${key}.webp`;
}

export type PremiumCardArt = {
  /** Always resolves — the fallback URL when the card has no art of its own. */
  url: string;
  /** True when `url` is the shared generic fallback, not per-card art. */
  fallback: boolean;
};

/** Art for the premium card face — always resolves (fallback baked in). */
export function premiumCardArt(name: CardName): PremiumCardArt {
  const url = cardArtUrl(name);
  return url === undefined ?
    {url: CARD_ART_FALLBACK_URL, fallback: true} :
    {url, fallback: false};
}
