/*
 * The CLIENT's copy of the Mars Parliament catalog (Turmoil Redux): every
 * resolution's printed face and every party's printed effect, generated by
 * `npm run make:cards` into `genfiles/parliament.json` — the global-event
 * manifest's twin. Static, never game state: the live parliament rides
 * `GameModel.parliament` and names cards by id.
 */
import {IClientPartyEffect, IClientResolution, ParliamentCatalog} from '@/common/parliament/IClientResolution';
import {ReduxParty, ResolutionId} from '@/common/parliament/ParliamentTypes';
// @ts-ignore parliament.json doesn't exist during npm run build
import parliamentJson from '@/genfiles/parliament.json';

const catalog = parliamentJson as any as ParliamentCatalog;
const resolutions: Map<ResolutionId, IClientResolution> = new Map();
const parties: Map<ReduxParty, IClientPartyEffect> = new Map();
for (const resolution of catalog.resolutions ?? []) {
  resolutions.set(resolution.id, resolution);
}
for (const party of catalog.parties ?? []) {
  parties.set(party.party, party);
}

export function allResolutions(): ReadonlyArray<IClientResolution> {
  return Array.from(resolutions.values());
}

export function getResolution(id: ResolutionId): IClientResolution | undefined {
  return resolutions.get(id);
}

export function getResolutionOrThrow(id: ResolutionId): IClientResolution {
  const resolution = resolutions.get(id);
  if (resolution === undefined) {
    throw new Error(`resolution ${id} not found`);
  }
  return resolution;
}

/** The display name of a resolution — an English i18n key — or the raw id for an unknown one (never a blank chip). */
export function resolutionName(id: ResolutionId): string {
  return resolutions.get(id)?.text.name ?? id;
}

export function getPartyEffect(party: ReduxParty): IClientPartyEffect | undefined {
  return parties.get(party);
}

export function allPartyEffects(): ReadonlyArray<IClientPartyEffect> {
  return Array.from(parties.values());
}
