export const paths = {
  ADMIN: 'admin',
  API_CLONEABLEGAME: 'api/cloneablegame',
  API_CREATEGAME: 'api/creategame',
  API_GAME: 'api/game',
  API_GAME_DELETE: 'api/game/delete',
  API_GAME_HISTORY: 'api/game/history',
  API_GAME_LOGS: 'api/game/logs',
  API_GAME_JOURNAL_EVENTS: 'api/game/journal-events',
  API_GAME_EFFECT_STATS: 'api/game/effect-stats',
  API_GAME_ACTION_STATS: 'api/game/action-stats',
  API_GAME_ENDGAME_FACTS: 'api/game/endgame-facts',
  API_GAME_DELTA_PREVIEW: 'api/game/delta-preview',
  API_GAME_BOARD_CELL_PREVIEW: 'api/game/board-cell-preview',
  API_GAME_COLONY_TRADE_PREVIEW: 'api/game/colony-trade-preview',
  API_GAME_REMATCH: 'api/game/rematch',
  API_GAMES: 'api/games',
  // Premium main-menu join flow: list a player's unfinished games by name, and
  // reconcile a seat's cube colour with the player's chosen identity colour.
  API_GAMES_JOINABLE: 'api/games/joinable',
  API_GAME_PLAYER_COLOR: 'api/game/player-color',
  API_IPS: 'api/ips',
  API_METRICS: 'api/metrics',
  API_LOGOUT: 'api/logout',
  API_PLAYER: 'api/player',
  API_PROFILE: 'api/profile',
  API_SPECTATOR: 'api/spectator',
  API_STATS: 'api/stats',
  API_WAITING_FOR: 'api/waitingfor',
  API_ACTION_PREVIEW: 'api/action-preview',
  API_CARD_PLAY_PREVIEW: 'api/card-play-preview',
  // Public desktop (Electron) compatibility + update-metadata endpoint (Phase 7).
  API_DESKTOP_VERSION: 'api/desktop/version',
  AUTH_DISCORD_CALLBACK: 'auth/discord/callback',
  AUTOPASS: 'autopass',
  CARDS: 'cards',
  GAME: 'game',
  GAMES_OVERVIEW: 'games-overview',
  HELP: 'help',
  LEGACY: 'legacy',
  LOAD: 'load',
  LOAD_GAME: 'load_game',
  // Premium "Mission Control" create-game screen (the new default from the
  // premium main menu). Legacy NEW_GAME ('new-game') stays for the legacy menu.
  NEW_GAME_PREMIUM: 'create-game',
  LOGIN: 'login',
  NEW_GAME: 'new-game',
  PLAYER: 'player',
  PLAYER_INPUT: 'player/input',
  PLAYER_INPUT_BATCH: 'player/input-batch',
  ACKNOWLEDGE_DRAW: 'player/acknowledge-draw',
  RESET: 'reset',
  SPECTATOR: 'spectator',
  THE_END: 'the-end',
  // Realtime WebSocket upgrade path. Not an HTTP handler in requestProcessor —
  // it is matched on the server's `upgrade` event (see RealtimeServer) and used
  // by the client to build the ws(s):// URL. A normal GET /ws still 404s.
  WEBSOCKET: 'ws',
} as const;
